# .graphclientrc.yml
sources:
  - name: uniswapv2
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2

documents:
  - ./queries/example-query.graphql
  - ./queries/aave-queries.graphql